from pathlib import Path

APP_NAME = "BC250 LLM MODE"
AMD_VENDOR_ID = "0x1002"
FAST_VRAM_GIB = 12.0
COMFORTABLE_VRAM_GIB = 10.5
GTT_SPILL_GIB = 2.5
OVERHEAD_GIB = 1.0
DEFAULT_CONTAINER = "llm"
DEFAULT_SERVICE = "bc250-llm.service"
DEFAULT_PORT = 8080
DEFAULT_CTX = 8192
DEFAULT_APP_DIR = Path.home() / ".bc250-llm-mode"
DEFAULT_STATE_PATH = DEFAULT_APP_DIR / "state.json"
DEFAULT_MODELS_DIR = DEFAULT_APP_DIR / "models"
DEFAULT_LOGS_DIR = DEFAULT_APP_DIR / "logs"

