from __future__ import annotations

import json
import os
import pwd
import shutil
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from .logging_utils import CommandRunner
from .optimize import normalized_settings
from .privilege import elevated


def require_safe_start(state: dict[str, Any]) -> None:
    """Read committed safety truth immediately before every start effect."""
    from .services import ThermalLatchProtected, ThermalStateService

    latch = state.get("thermal_watchdog_state", "nominal")
    app_dir = state.get("app_dir")
    if app_dir:
        database = Path(str(app_dir)).expanduser() / "state.db"
        if not database.is_file():
            raise ThermalLatchProtected("Safety state unavailable; run Repair before starting.")
        latch = ThermalStateService.for_database(database).current()["latch_state"]
    if latch == "stopped":
        raise ThermalLatchProtected("Thermal stop is latched. Let the GPU cool and explicitly reset the latch before starting.")


def current_model_record(state: dict[str, Any]) -> dict[str, Any]:
    model_id = state.get("current_model")
    for record in state.get("installed_models", []):
        if record.get("id") == model_id:
            return record
    raise RuntimeError("No current installed model is selected")


def observed_model_matches_selected(
    state: dict[str, Any], observed_model: Any,
) -> bool:
    """Match llama.cpp's public alias to the selected durable model id.

    The launcher intentionally publishes a friendly ``display_name`` through
    llama.cpp's ``--alias``.  Local imports use a separate stable internal id
    (for example ``local-a3515b591cfc``), so both identities are valid proof
    of the same selected installation.
    """
    if observed_model is None:
        return False
    observed = str(observed_model)
    selected = state.get("current_model")
    if selected is not None and observed == str(selected):
        return True
    for record in state.get("installed_models", []):
        if record.get("id") != selected:
            continue
        public_alias = str(
            record.get("display_name") or selected or ""
        ).replace("\n", " ").strip()
        duplicates = sum(str(item.get("display_name") or item.get("id") or "").replace("\n", " ").strip() == public_alias for item in state.get("installed_models", []))
        return bool(public_alias and observed == public_alias and duplicates == 1)
    return False


LAUNCHER_TEMPLATE = """#!/usr/bin/env bash
# Generated by bc250-llm-mode. Consumes ONLY runtime-handoff.json (mode 0600,
# rendered from SQLite). A missing or invalid handoff fails closed: run
# 'bc250-llm-mode llm restart' to regenerate it from current database state.
set -euo pipefail
HANDOFF="${BC250_HANDOFF_PATH:-@HANDOFF@}"
ARGV=()
FAST_SYNC=0
append_argv() {
  while IFS= read -r argv_line; do
    ARGV+=("$argv_line")
  done
}
if [ ! -f "$HANDOFF" ]; then
  echo "bc250-llm-mode: runtime handoff missing at $HANDOFF; refusing to start." >&2
  echo "Regenerate it from SQLite with 'bc250-llm-mode llm restart'." >&2
  exit 78
fi
FAST_SYNC=$(python3 -c 'import json, sys; h=json.load(open(sys.argv[1])); print(1 if h.get("fast_sync") else 0)' "$HANDOFF")
ARGV_FILE=$(mktemp)
trap 'rm -f "$ARGV_FILE"' EXIT
if ! python3 - "$HANDOFF" >"$ARGV_FILE" <<'PYH'
import json
import os
import sys

h = json.load(open(sys.argv[1], encoding="utf-8"))

# Strict handoff validation (fail closed): schema, revision, identity,
# and bounded numerics. Anything unexpected refuses to launch.
REQUIRED = (
    "schema_version", "config_revision", "runtime_fingerprint",
    "model_id", "model_path", "alias", "llama_cpp_path",
    "port", "ctx_total", "parallel_slots",
    "flash_attention", "batch_size", "ubatch_size", "kv_cache_type",
)
missing = [key for key in REQUIRED if key not in h]
if missing:
    sys.exit("handoff invalid: missing fields: " + ", ".join(missing))
SCHEMA = int(h["schema_version"])
if SCHEMA not in (1, 2):
    sys.exit("handoff invalid: unsupported schema_version")
IDENTITY_KEYS = (
    "runtime_component_id", "runtime_source_commit",
    "runtime_server_sha256", "runtime_manifest_digest",
    "runtime_operation_id",
)
if SCHEMA == 2:
    missing_identity = [key for key in IDENTITY_KEYS if key not in h]
    if missing_identity:
        sys.exit("handoff invalid: missing component identity fields: "
                 + ", ".join(missing_identity))
    for key in ("runtime_server_sha256", "runtime_manifest_digest"):
        value = str(h[key])
        if len(value) != 64 or any(c not in "0123456789abcdef"
                                   for c in value):
            sys.exit("handoff invalid: " + key + " is not a sha256 hex")
rev = h["config_revision"]
if not isinstance(rev, int) or rev < 1:
    sys.exit("handoff invalid: config_revision")
port = int(h["port"])
if not 1024 <= port <= 65535:
    sys.exit("handoff invalid: port out of range")
slots = int(h["parallel_slots"])
if not 1 <= slots <= 8:
    sys.exit("handoff invalid: parallel_slots out of range")
ctx_total = int(h["ctx_total"])
if ctx_total < slots * 512 or ctx_total > 262144 * slots:
    sys.exit("handoff invalid: ctx_total out of range")
for key in ("batch_size", "ubatch_size"):
    value = int(h[key])
    if not 16 <= value <= 8192:
        sys.exit(f"handoff invalid: {key} out of range")
if not str(h["model_path"]):
    sys.exit("handoff invalid: empty model_path")
if not str(h["alias"]).strip():
    sys.exit("handoff invalid: empty alias")

argv = [
    os.path.join(h["llama_cpp_path"], "build", "bin", "llama-server"),
    "-m", h["model_path"],
    "--host", "127.0.0.1",
    "--port", str(h["port"]),
    "--n-gpu-layers", "99",
    "--ctx-size", str(h["ctx_total"]),
    "--flash-attn", h["flash_attention"],
    "--batch-size", str(h["batch_size"]),
    "--ubatch-size", str(h["ubatch_size"]),
    "--cache-type-k", h["kv_cache_type"],
    "--cache-type-v", h["kv_cache_type"],
    "--parallel", str(h["parallel_slots"]),
    "--metrics",
    "--alias", h["alias"],
    "--temp", str(h.get("temperature", 0.3)),
    "--top-p", str(h.get("top_p", 0.9)),
    "--top-k", str(h.get("top_k", 40)),
    "--min-p", str(h.get("min_p", 0.05)),
    "--repeat-penalty", str(h.get("repeat_penalty", 1.05)),
]
threads = h.get("threads")
cores = set()
socket_id = None
try:
    info = open("/proc/cpuinfo", encoding="utf-8").read()
    for line in info.splitlines():
        parts = line.split(":", 1)
        if len(parts) != 2:
            continue
        key = parts[0].strip()
        value = parts[1].strip()
        if key == "physical id":
            socket_id = value
        elif key == "core id" and socket_id is not None:
            cores.add((socket_id, value))
            socket_id = None
    detected = len(cores) or sum(
        1 for entry in info.splitlines() if entry.startswith("processor"))
except OSError:
    detected = 0
if not (isinstance(threads, int) and 1 <= threads <= 64):
    threads = detected
if isinstance(threads, int) and threads >= 1:
    argv += ["--threads", str(threads), "--threads-batch", str(threads)]
# Use llama.cpp's supported long spelling so the generated launcher remains
# readable while matching both current and older supported builds.
argv += ["--cache-reuse", "256", "--defrag-thold", "0.1"]
for item in argv:
    print(item)
PYH
then
  exit 78
fi
append_argv < "$ARGV_FILE"
rm -f "$ARGV_FILE"
trap - EXIT
# U1.2 (ADR 004 D5/§14.2): before exec, bind the handoff to the ACTIVE
# runtime component. A v2 handoff MUST match the active tree manifest and
# the real server binary; a 0600 start receipt is published on success.
python3 - "$HANDOFF" <<'PYRECEIPT' >&2
import hashlib, json, os, sys, time

h = json.load(open(sys.argv[1], encoding="utf-8"))
if int(h.get("schema_version", 1)) < 2:
    sys.exit(0)  # legacy artifact: no component binding to verify


def die(msg):
    sys.stderr.write("bc250-llm-mode: " + msg + chr(10))
    sys.exit(78)


component = str(h.get("runtime_component_id", "")).strip()
manifest_digest = str(h.get("runtime_manifest_digest", ""))
server_sha = str(h.get("runtime_server_sha256", ""))
if not component or len(manifest_digest) != 64 or len(server_sha) != 64:
    die("runtime handoff v2 has an incomplete component identity")
root = h["llama_cpp_path"]
manifest_path = os.path.join(root, "manifest.json")
if not os.path.isfile(manifest_path):
    die("active runtime manifest missing at " + manifest_path)
manifest = json.load(open(manifest_path, encoding="utf-8"))
if manifest.get("build_id") != component:
    die("active runtime manifest does not match the expected build id")
if manifest.get("manifest_digest") != manifest_digest:
    die("runtime manifest digest mismatch")
binary_path = os.path.join(root, "build", "bin", "llama-server")
digest = hashlib.sha256()
with open(binary_path, "rb") as handle:
    for chunk in iter(lambda: handle.read(1 << 20), b""):
        digest.update(chunk)
if digest.hexdigest() != server_sha:
    die("llama-server binary digest mismatch")
entry = next((e for e in (manifest.get("manifest", {}).get("binaries") or [])
              if str(e.get("path", "")).endswith("llama-server")), None)
if entry and entry.get("sha256") != server_sha:
    die("manifest binary entry mismatch")
receipt_dir = os.path.dirname(os.path.abspath(sys.argv[1]))
receipt = {
    "build_id": component,
    "server_sha256": server_sha,
    "manifest_digest": manifest_digest,
    "operation_id": str(h.get("runtime_operation_id", "")),
    "nonce": str(os.getpid()) + "-" + str(int(time.time() * 1000)),
}
tmp_path = os.path.join(receipt_dir, ".start-receipt.tmp")
with open(tmp_path, "w", encoding="utf-8") as handle:
    json.dump(receipt, handle, indent=2, sort_keys=True)
os.chmod(tmp_path, 0o600)
os.replace(tmp_path, os.path.join(receipt_dir, "start-receipt.json"))
sys.exit(0)
PYRECEIPT
export GGML_VK_DISABLE_F16=1
if [ "$FAST_SYNC" != "1" ]; then
  export GGML_VK_FORCE_SYNC=1
fi
exec "${ARGV[@]}"
"""


def generate_launcher(state: dict[str, Any]) -> Path:
    """Generate the runtime launcher (handoff-only; no JSON fallback).

    The launcher consumes ``runtime-handoff.json`` — the rendered artifact
    of the committed SQLite state — and fails closed when it is missing or
    invalid. Controlled start/restart regenerates the handoff first; the
    immutable legacy ``state.json`` is never a launch source.
    """
    app_dir = Path(str(state["app_dir"])).expanduser()
    app_dir.mkdir(parents=True, exist_ok=True)
    launcher = app_dir / "run-model.sh"
    handoff_path = app_dir / "runtime-handoff.json"
    content = LAUNCHER_TEMPLATE.replace("@HANDOFF@", str(handoff_path))
    launcher.write_text(content, encoding="utf-8")
    launcher.chmod(0o755)
    return launcher

def _service_text(state: dict[str, Any], launcher: Path) -> str:
    container = state.get("container_name", "llm")
    uid = os.getuid()
    account = pwd.getpwuid(uid)
    identity = ""
    if uid:
        identity = (
            f"User={account.pw_name}\nGroup={account.pw_gid}\n"
            f"Environment=HOME={account.pw_dir}\nEnvironment=XDG_RUNTIME_DIR=/run/user/{uid}\n"
        )
    podman = shutil.which("podman") or "/usr/bin/podman"
    # The supervisor is part of this explicitly started service, never an
    # autostart unit. Every automatic restart rechecks committed safety first.
    def unit_arg(value):
        return '"' + str(value).replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"') + '"'
    supervised_command = " ".join(unit_arg(arg) for arg in (
        os.path.abspath(sys.executable), "-m", "bc250_llm_mode.runtime_policy",
        "--profile", launcher.parent, "--", podman, "exec", "--user", "root", container, launcher))
    cleanup_check = " ".join(unit_arg(arg) for arg in (podman, "exec", "--user", "root", container, "/usr/bin/test", "-x", "/usr/bin/pkill"))
    guest_cleanup = " ".join(unit_arg(arg) for arg in (podman, "exec", "--user", "root", container, "/usr/bin/pkill", "-KILL", "-x", "llama-server"))
    runtime_prep = ""
    if uid == 0:
        install = shutil.which("install") or "/usr/bin/install"
        # Root-created Distrobox containers bind-mount /run/user/0. That path
        # is volatile and may not exist on a headless boot until root logs in.
        runtime_prep = f"ExecStartPre={install} -d -m 0700 -o 0 -g 0 /run/user/0\n"
    # Bazzite maps /root to /var/roothome. systemd/SELinux can reject an
    # append: output target there with status 209/STDOUT before ExecStart runs.
    # /var/log is the appropriate system-service log location.
    server_log = (
        "/var/log/bc250-llm-server.log"
        if uid == 0
        else str(Path(str(state["logs_dir"])).expanduser() / "llama-server.log")
    )
    state["server_log"] = server_log
    tuning = normalized_settings(state.get("optimizations"))
    limits = ""
    resource_guards = ""
    restart_delay = 10
    if tuning["safeguards_enabled"]:
        limits = (
            f"StartLimitIntervalSec={int(tuning['restart_window_sec'])}\n"
            f"StartLimitBurst={int(tuning['restart_burst'])}\n"
        )
        restart_delay = int(tuning["restart_delay_sec"])
        # The host only owns ~4 GiB after the 12/4 UMA carve-out. Capping the
        # service means the OOM killer and systemd take out the *server*, never
        # the Bazzite desktop, and the server yields I/O to interactive use.
        resource_guards = (
            "MemoryHigh=3000M\nMemoryMax=3500M\nOOMScoreAdjust=500\n"
            "IOSchedulingClass=idle\n"
        )
    return f"""[Unit]
Description=BC250 llama.cpp model server
After=network-online.target
Wants=network-online.target
{limits}

[Service]
{identity}{runtime_prep}{resource_guards}ExecStartPre=-{podman} start {container}
ExecStartPre={cleanup_check}
ExecStart={supervised_command}
# Podman exec's guest process can outlive an abruptly killed host client.
# The dedicated managed guest has one canonical llama-server owner.
ExecStopPost=-{guest_cleanup}
TimeoutStopSec=15
KillMode=control-group
Restart=on-failure
RestartSec={restart_delay}
StandardOutput=append:{server_log}
StandardError=append:{server_log}

[Install]
WantedBy=multi-user.target
"""


def install_service(
    state: dict[str, Any], runner: CommandRunner, *, enable_and_start: bool = True
) -> Path:
    from .runtime_handoff import regenerate_for_app_state

    regenerate_for_app_state(state)
    launcher = generate_launcher(state)
    service_name = str(state.get("service_name", "bc250-llm.service"))
    destination = Path("/etc/systemd/system") / service_name
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as handle:
        handle.write(_service_text(state, launcher))
        temporary = handle.name
    try:
        runner.run(elevated(["install", "-m", "0644", temporary, str(destination)]))
    finally:
        try:
            os.unlink(temporary)
        except OSError:
            pass
    runner.run(elevated(["systemctl", "daemon-reload"]))
    if os.getuid():
        runner.run(elevated(["loginctl", "enable-linger", pwd.getpwuid(os.getuid()).pw_name]), check=False)
    if enable_and_start:
        # LLM Mode is a current-boot session. Never leave inference enabled
        # across reboot; start it explicitly for this boot only.
        runner.run(elevated(["systemctl", "disable", service_name]), check=False)
        require_safe_start(state)
        runner.run(elevated(["systemctl", "start", service_name]))
        state.update(boot_policy="desktop", desktop_on_reboot=True, llm_autostart=False)
    else:
        runner.emit(f"Refreshed {service_name} definition without changing its enabled/running state")
    state["setup_phase"] = max(int(state.get("setup_phase", 0)), 9)
    return destination


def service_observation(state: dict[str, Any], runner: CommandRunner) -> dict[str, Any]:
    """Read-only systemd observation; never mutates or toggles enablement."""
    service = str(state.get("service_name", "bc250-llm.service"))
    result = runner.run(
        elevated(["systemctl", "is-active", service]), check=False
    )
    active = result.returncode == 0 and result.stdout.strip() == "active"
    return {"service": service, "active": active}


def restart_service(state: dict[str, Any], runner: CommandRunner) -> None:
    # Refresh the launcher and regenerate a missing/stale runtime handoff on
    # every controlled restart so newly added per-model profiles and any
    # committed-but-unrendered changes take effect without reinstalling.
    # Restart never changes enablement: desktop-next-boot is untouched.
    from .runtime_handoff import regenerate_for_app_state

    require_safe_start(state)
    install_service(state, runner, enable_and_start=False)
    require_safe_start(state)
    runner.run(elevated(["systemctl", "restart", str(state["service_name"])]))


def _unit_property(runner: CommandRunner, service: str, prop: str) -> str:
    result = runner.run(
        ["systemctl", "show", service, f"--property={prop}", "--value"], check=False
    )
    return result.stdout.strip()


def invocation_marker(state: dict[str, Any], runner: CommandRunner) -> str | None:
    """The current systemd invocation identity (start timestamp).

    A NEW successful invocation after a swap must present a DIFFERENT
    marker than the one captured before it (ADR 004 D5 item 5).
    """
    service = str(state.get("service_name", "bc250-llm.service"))
    load = _unit_property(runner, service, "LoadState")
    if load == "not-found":
        return None
    return _unit_property(runner, service, "ExecMainStartTimestamp") or None


def capture_service_state(
    state: dict[str, Any], runner: CommandRunner,
) -> dict[str, Any]:
    """Read-only ``(active, invocation_marker)`` facts for the port."""
    status = service_status(state, runner)
    return {
        "active": bool(status.get("active")),
        "invocation_marker": invocation_marker(state, runner),
    }


def service_status(state: dict[str, Any], runner: CommandRunner) -> dict[str, Any]:
    """Return live systemd state without assuming the service is installed."""
    service = str(state.get("service_name", "bc250-llm.service"))
    load = _unit_property(runner, service, "LoadState")
    active = _unit_property(runner, service, "ActiveState") if load != "not-found" else "inactive"
    sub = _unit_property(runner, service, "SubState") if load != "not-found" else "dead"
    unit_file = _unit_property(runner, service, "UnitFileState") if load != "not-found" else "disabled"
    return {
        "service": service,
        "installed": bool(load and load != "not-found"),
        "load_state": load or "unknown",
        "active": active == "active",
        "active_state": active or "unknown",
        "sub_state": sub or "unknown",
        "enabled": unit_file in {"enabled", "enabled-runtime", "static"},
        "unit_file_state": unit_file or "unknown",
    }


def start_service(
    state: dict[str, Any], runner: CommandRunner, *, wait_for_health: bool = True
) -> dict[str, Any]:
    """Start only the systemd-owned llama server, optionally waiting for its API."""
    current_model_record(state)
    require_safe_start(state)
    install_service(state, runner, enable_and_start=False)
    require_safe_start(state)
    runner.run(elevated(["systemctl", "start", str(state["service_name"])]))
    if wait_for_health:
        return health_check(state, runner)
    return service_status(state, runner)


def stop_service(state: dict[str, Any], runner: CommandRunner) -> dict[str, Any]:
    service = str(state["service_name"])
    runner.run(elevated(["systemctl", "stop", service]), check=False)
    # Podman's attached exec can report a nonzero exit while llama-server is
    # gracefully terminating. An explicit user Stop should settle at inactive,
    # while genuine unexpected failures still retain Restart=on-failure.
    runner.run(elevated(["systemctl", "reset-failed", service]), check=False)
    return service_status(state, runner)


def restart_and_wait(state: dict[str, Any], runner: CommandRunner) -> dict[str, Any]:
    current_model_record(state)
    restart_service(state, runner)
    return health_check(state, runner)


def _json_get(url: str, timeout: float = 5) -> Any:
    with urllib.request.urlopen(url, timeout=timeout) as response:
        return json.load(response)


def local_server_readiness(
    state: dict[str, Any], *, timeout: float = 1.5
) -> dict[str, Any]:
    """Observe the local llama endpoint once without mutating durable state.

    Chat uses this short, worker-thread probe to avoid confusing missing or
    stale historical inference evidence with a server that is ready now.
    Both the health endpoint and the loaded-model identity must agree with the
    selected model before the result is ready.
    """
    port = int(state.get("server_port", 8080))
    health = _json_get(f"http://127.0.0.1:{port}/health", timeout=timeout)
    models = _json_get(f"http://127.0.0.1:{port}/v1/models", timeout=timeout)
    data = models.get("data") if isinstance(models, dict) else None
    observed_model = (
        data[0].get("id")
        if isinstance(data, list) and data and isinstance(data[0], dict)
        else None
    )
    desired_model = state.get("current_model")
    health_ok = isinstance(health, dict) and str(
        health.get("status") or ""
    ).lower() in {"ok", "ready", "healthy"}
    return {
        "healthy": health_ok and bool(observed_model),
        "model_id": observed_model,
        "desired_model": desired_model,
        "model_matches_desired": observed_model_matches_selected(
            state, observed_model
        ),
    }


def minimal_inference_probe(state: dict[str, Any], timeout: float = 20.0) -> dict[str, Any]:
    """Bounded single-token completion proving real generation works.

    Used by activation verification: /health only proves the process is up;
    this proves the model actually produces tokens. Connect, write, and
    total timeouts are all bounded.
    """
    port = int(state.get("server_port", 8080))
    alias = str((state.get("installed_models") and next(
        (m.get("display_name") or m.get("id") for m in state["installed_models"]
         if m.get("id") == state.get("current_model")), state.get("current_model"),
    )) or "local").replace("\n", " ").strip()
    body = json.dumps({
        "model": alias,
        "messages": [{"role": "user", "content": "ping"}],
        "max_tokens": 1,
        "stream": False,
    }).encode("utf-8")
    request = urllib.request.Request(
        f"http://127.0.0.1:{port}/v1/chat/completions",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        payload = json.load(response)
    text = ((payload.get("choices") or [{}])[0].get("message") or {}).get("content")
    if not isinstance(text, str):
        raise RuntimeError("inference probe returned no completion content")
    return {"ok": True, "sample": text[:64]}


def health_check(
    state: dict[str, Any],
    runner: CommandRunner | None = None,
    timeout: int = 120,
    *,
    monotonic: Any = None,
    sleep: Any = None,
    pulse: Any = None,
) -> dict[str, Any]:
    """Bounded health polling with an injected clock (Session 5C §10.3).

    ``pulse`` is the durable-operation heartbeat.  A normal model load can
    legitimately take longer than the 60-second operation lease, so every
    poll renews the caller's fence while the server is starting.
    """
    monotonic = monotonic or time.monotonic
    sleep = sleep or time.sleep
    port = int(state.get("server_port", 8080))
    deadline = monotonic() + timeout
    last_error = "server did not respond"
    while monotonic() < deadline:
        if pulse is not None:
            pulse()
        try:
            health = _json_get(f"http://127.0.0.1:{port}/health")
            models = _json_get(f"http://127.0.0.1:{port}/v1/models")
            try:
                props = _json_get(f"http://127.0.0.1:{port}/props")
            except (OSError, urllib.error.URLError, ValueError):
                props = {}
            actual_ctx = (
                props.get("default_generation_settings", {}).get("n_ctx")
                if isinstance(props, dict)
                else None
            )
            metrics = system_metrics()
            # §11.2: the OBSERVED model comes from the live server only.
            # The desired ``current_model`` is never proof of a live model.
            observed_model = None
            if isinstance(props, dict) and props.get("model_alias"):
                observed_model = props.get("model_alias")
            elif isinstance(models, dict):
                data = models.get("data") or []
                if data and isinstance(data[0], dict):
                    observed_model = data[0].get("id")
            desired_model = state.get("current_model")
            observed_slots = int(
                props.get("total_slots")
                if isinstance(props, dict) and props.get("total_slots") is not None
                else normalized_settings(state.get("optimizations"))["parallel_slots"]
            )
            context_per_slot = int(actual_ctx or state.get("current_ctx", 8192))
            result = {
                "healthy": True,
                "model_id": observed_model,
                "desired_model": desired_model,
                "model_matches_desired": observed_model_matches_selected(
                    state, observed_model
                ),
                # llama.cpp's /props ``n_ctx`` is the context available to
                # each parallel slot.  Publish both units explicitly so
                # activation never mistakes a healthy per-slot value for a
                # deficient total allocation.
                "n_ctx": context_per_slot,
                "context_per_slot": context_per_slot,
                "context_total": context_per_slot * observed_slots,
                "requested_ctx": int(state.get("current_ctx", 8192)),
                "parallel_slots": observed_slots,
                "vram_used_mib": metrics.get("vram_used_mib"),
                "vram_total_mib": metrics.get("vram_total_mib"),
                "health": health,
                "models": models,
                "model_alias": props.get("model_alias") if isinstance(props, dict) else None,
            }
            if runner:
                runner.emit(
                    f"Server healthy on 127.0.0.1:{port}; model={result['model_id']} "
                    f"(desired={desired_model}) "
                    f"context_per_slot={result['context_per_slot']} "
                    f"context_total={result['context_total']} "
                    f"VRAM={result['vram_used_mib']}/{result['vram_total_mib']} MiB"
                )
            if pulse is not None:
                pulse()
            return result
        except (OSError, urllib.error.URLError, ValueError) as exc:
            last_error = str(exc)
            sleep(2)
    if runner:
        show_server_failure(state, runner, last_error)
    raise TimeoutError(f"Model server was not healthy within {timeout}s: {last_error}")


def diagnose_server_log(text: str) -> str:
    lower = text.lower()
    if "erroroutofdevicememory" in lower and any(word in lower for word in ("max", "fused", "imatrix")):
        return "This is a fused MAX repack; it cannot load on this card. Choose a standard-layout catalog model."
    if "missing tensor" in lower and "nextn" in lower:
        return "MTP metadata mismatch detected; run the nextn metadata repair."
    if "missing tensor" in lower and "blk." in lower:
        return "Block-count metadata mismatch detected; run GGUF verification/repair."
    if "vulkan" in lower and any(word in lower for word in ("fail", "error", "no device")):
        return "Vulkan initialization failed; re-run inference environment setup."
    if "erroroutofdevicememory" in lower:
        return "GPU allocation failed. Choose a smaller quant/context and verify the BIOS 12 GiB UMA allocation."
    if "no module named" in lower:
        return "The inference environment is incomplete; re-run environment setup."
    return "Review the server log above; it is the ground truth for model load failures."


def show_server_failure(state: dict[str, Any], runner: CommandRunner, error: str = "") -> str:
    server_log = str(state.get("server_log", "/root/llama-server.log"))
    command = ["tail", "-n", "120", server_log]
    result = runner.run(elevated(command) if server_log.startswith("/root/") else command, check=False)
    guidance = diagnose_server_log(result.stdout)
    runner.emit(f"Server health failure: {error}")
    runner.emit(f"Guidance: {guidance}")
    return guidance


def ensure_server(state: dict[str, Any], runner: CommandRunner) -> dict[str, Any]:
    """Self-healing entry point: healthy stays up, stopped starts, sick restarts."""
    status = service_status(state, runner)
    if not status.get("active"):
        if not state.get("current_model"):
            raise RuntimeError("No model is installed yet; complete setup before ensuring the server")
        if runner:
            runner.emit("Model server is stopped; starting it and waiting for health")
        return {"ensured": "started", **restart_and_wait(state, runner)}
    try:
        health = health_check(state, timeout=3)
    except (OSError, urllib.error.URLError, TimeoutError, ValueError, RuntimeError) as exc:
        if runner:
            runner.emit(f"Active server is unhealthy ({exc}); restarting it")
        return {"ensured": "restarted", **restart_and_wait(state, runner)}
    return {"ensured": "already-healthy", **health}


def system_metrics() -> dict[str, Any]:
    # Discover on every invocation because cardN renumbers.
    from .hardware import _bytes_to_mib, _read_text, find_amd_gpu

    gpu = find_amd_gpu()
    if not gpu:
        return {"error": "No AMD GPU found"}
    hwmon_values: dict[str, str] = {}
    for hwmon in (gpu / "hwmon").glob("hwmon*"):
        for filename in ("temp1_input", "freq1_input", "power1_average"):
            value = _read_text(hwmon / filename)
            if value:
                hwmon_values[filename] = value
    return {
        "gpu_path": str(gpu),
        "vram_used_mib": _bytes_to_mib(_read_text(gpu / "mem_info_vram_used")),
        "vram_total_mib": _bytes_to_mib(_read_text(gpu / "mem_info_vram_total")),
        **hwmon_values,
    }
